rule all:
    input:
        "article.pdf",
        "talk.pdf"

rule article:
    input: "article.tex"
    output: "article.pdf"
    shell:
        """
        latexmk --xelatex -output-directory=article article.tex
        cp article/article.pdf .
        """

rule talk:
    input: "talk.tex"
    output: "talk.pdf"
    shell:
        """
        latexmk --xelatex -output-directory=talk talk.tex
        cp talk/talk.pdf .
        """
