rule all:
    input:
        "article.pdf",
        "talk.pdf"

rule article:
    input:
        "../../templates/article.tex",
        "article.qmd"
    output: "article.pdf"
    shell: "quarto render article.qmd"

rule talk:
    input:
        "../../templates/slides.tex",
        "talk.qmd"
    output: "talk.pdf"
    shell: "quarto render talk.qmd"
